
package gui;

import database.IBilgiController;
import database.transactons.HesapBilgileri;
import database.transactons.TelNoYenile;
import gui.ayarlari.ActionAyarlari;
import gui.ayarlari.Dialogs;
import gui.ayarlari.IDuzenleyici;
import gui.ayarlari.IconAyarlari;
import gui.ayarlari.TextAyarlari;
import javax.swing.JOptionPane;


public class ayarlarEkrani extends javax.swing.JFrame implements IDuzenleyici,IBilgiController{

    private TelNoYenile telNoYenileObject=null;
    
    private String eskiTelNo =null;
    private int clickCounter=0;
    
    public ayarlarEkrani() {
        initComponents();
        getEdits();
        
    }

    @Override
    public void getEdits() {
    this.setLocationRelativeTo(null);
    this.setResizable(false);
    this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    ekranAyarlariPanel.setFocusable(true);
        TextAyarlari.setOnlyNumber(telNoText);
        TextAyarlari.setMaxLimit(telNoText, 11);
        this.telNoText.setText(getHesapBilgileri().getTelNo());
        eskiTelNo=telNoText.getText();
        this.kullaniciAdiSoyadiLabel.setText(getHesapBilgileri().getAdSoyad());
        
    }

    @Override
    public boolean bilgilerGecerliMi() {
     return !(this.telNoText.getText().equals(""));
    }

    @Override
    public HesapBilgileri getHesapBilgileri() {
       return HesapBilgileri.getInstance();
    }

    public TelNoYenile getTelNoYenileObject() {
        if(telNoYenileObject==null)
        {
            telNoYenileObject=new TelNoYenile();
        }
        return telNoYenileObject;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ekranAyarlariPanel = new javax.swing.JPanel();
        geriIcon3 = new javax.swing.JLabel();
        kullaniciAdiSoyadiLabel = new javax.swing.JLabel();
        telNoLabel = new javax.swing.JLabel();
        telNoText = new javax.swing.JTextField();
        telNoIcon = new javax.swing.JLabel();
        sifreLabel = new javax.swing.JLabel();
        sifreText = new javax.swing.JTextField();
        sifreIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ayarlar Ekranı");
        setResizable(false);

        ekranAyarlariPanel.setBackground(new java.awt.Color(204, 255, 204));

        geriIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Iconlar/preiousIcon.png"))); // NOI18N
        geriIcon3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        geriIcon3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                geriIcon3MouseClicked(evt);
            }
        });

        kullaniciAdiSoyadiLabel.setBackground(new java.awt.Color(255, 204, 204));
        kullaniciAdiSoyadiLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        kullaniciAdiSoyadiLabel.setForeground(new java.awt.Color(153, 0, 0));
        kullaniciAdiSoyadiLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kullaniciAdiSoyadiLabel.setText("SAYIN [ADI SOYADI]");

        telNoLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        telNoLabel.setText("Telefon Numaranız :");

        telNoText.setEnabled(false);

        telNoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Iconlar/updateIcon.png"))); // NOI18N
        telNoIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        telNoIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                telNoIconMouseClicked(evt);
            }
        });

        sifreLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sifreLabel.setText("Şifreniz :");

        sifreIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Iconlar/updateIcon.png"))); // NOI18N
        sifreIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sifreIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sifreIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ekranAyarlariPanelLayout = new javax.swing.GroupLayout(ekranAyarlariPanel);
        ekranAyarlariPanel.setLayout(ekranAyarlariPanelLayout);
        ekranAyarlariPanelLayout.setHorizontalGroup(
            ekranAyarlariPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ekranAyarlariPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ekranAyarlariPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ekranAyarlariPanelLayout.createSequentialGroup()
                        .addComponent(geriIcon3)
                        .addGroup(ekranAyarlariPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ekranAyarlariPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addComponent(telNoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(telNoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
                            .addGroup(ekranAyarlariPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(kullaniciAdiSoyadiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61))))
                    .addGroup(ekranAyarlariPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sifreLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sifreText, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sifreIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );

        ekranAyarlariPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {sifreText, telNoText});

        ekranAyarlariPanelLayout.setVerticalGroup(
            ekranAyarlariPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ekranAyarlariPanelLayout.createSequentialGroup()
                .addGroup(ekranAyarlariPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ekranAyarlariPanelLayout.createSequentialGroup()
                        .addGroup(ekranAyarlariPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ekranAyarlariPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(geriIcon3))
                            .addGroup(ekranAyarlariPanelLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(kullaniciAdiSoyadiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(ekranAyarlariPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ekranAyarlariPanelLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(telNoIcon)))
                .addGroup(ekranAyarlariPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ekranAyarlariPanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(ekranAyarlariPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sifreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sifreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ekranAyarlariPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sifreIcon)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        ekranAyarlariPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {sifreText, telNoLabel, telNoText});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ekranAyarlariPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ekranAyarlariPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void geriIcon3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geriIcon3MouseClicked
        ActionAyarlari.setVisible(this, new hesapEkrani());
    }//GEN-LAST:event_geriIcon3MouseClicked

    private void telNoIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telNoIconMouseClicked
       
       if(clickCounter==0)
       {
           telNoText.setEnabled(true);
           IconAyarlari.changeIcon(telNoIcon,"tickIcon");
           clickCounter++;
           
       }
       else
       {
           telNoText.setEnabled(false);
           IconAyarlari.setOriginalIcon(telNoIcon);
           this.telNoYenile();
           clickCounter=0;
       }
       
            
    }//GEN-LAST:event_telNoIconMouseClicked
      
    private void telNoYenile()
    {
        if(bilgilerGecerliMi())
        {
            String yeniTelNo=this.telNoText.getText().trim();
            getTelNoYenileObject().setTelNo(yeniTelNo);
            if(getTelNoYenileObject().TelNoYenilendiMi())
            {
                Dialogs.ozelMesaj(this, "Telefonunuz "+yeniTelNo+" olarak güncellenmiştir.");
            }else{
                Dialogs.ozelMesaj(this, "Başarısız. Bilgilerinizi kontrol ediniz!");
                this.telNoText.setText(this.eskiTelNo);
            }
        }else{
            Dialogs.bosOlamazMesaji(this);
            this.telNoText.setText(this.eskiTelNo);
        }
    }
    
    private void sifreIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sifreIconMouseClicked
        ActionAyarlari.setVisible(this, new sifreYenilemeEkrani());
    }//GEN-LAST:event_sifreIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ayarlarEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ayarlarEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ayarlarEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ayarlarEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ayarlarEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ekranAyarlariPanel;
    private javax.swing.JLabel geriIcon3;
    private javax.swing.JLabel kullaniciAdiSoyadiLabel;
    private javax.swing.JLabel sifreIcon;
    private javax.swing.JLabel sifreLabel;
    private javax.swing.JTextField sifreText;
    private javax.swing.JLabel telNoIcon;
    private javax.swing.JLabel telNoLabel;
    private javax.swing.JTextField telNoText;
    // End of variables declaration//GEN-END:variables
}
