/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import database.IBilgiController;
import database.transactons.HesapBilgileri;
import database.transactons.KullaniciBasvuru;
import gui.ayarlari.ActionAyarlari;
import gui.ayarlari.ButonAyarlari;
import gui.ayarlari.Dialogs;
import gui.ayarlari.IDuzenleyici;
import gui.ayarlari.TextAyarlari;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class basvuruEkrani extends javax.swing.JFrame implements IDuzenleyici,IBilgiController
{

    /**
     * Creates new form basvuruEkrani
     */
    
    private KullaniciBasvuru kullaniciBasvuruObject=null;
    
    public basvuruEkrani() {
        initComponents();
        getEdits();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basvuruEkraniPanel = new javax.swing.JPanel();
        kisiselBilgilerLabel = new javax.swing.JLabel();
        adSoyadLabel = new javax.swing.JLabel();
        adSoyadText = new javax.swing.JTextField();
        tcNoLabel = new javax.swing.JLabel();
        tcNoText = new javax.swing.JTextField();
        telNoLabel = new javax.swing.JLabel();
        telNoText = new javax.swing.JTextField();
        kisiselBilgilerLabel1 = new javax.swing.JLabel();
        GuvenlikSorusuLabel = new javax.swing.JLabel();
        guvenlikSorusu = new javax.swing.JComboBox<>();
        guvenlikCevabiLabel = new javax.swing.JLabel();
        guvenlikCevabiText = new javax.swing.JTextField();
        cevapButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Başvuru Ekranı");
        setResizable(false);

        basvuruEkraniPanel.setBackground(new java.awt.Color(153, 153, 153));

        kisiselBilgilerLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        kisiselBilgilerLabel.setText("Güvenlik Bilgileri");

        adSoyadLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        adSoyadLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        adSoyadLabel.setText("Cevap :");

        adSoyadText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adSoyadTextActionPerformed(evt);
            }
        });

        tcNoLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tcNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tcNoLabel.setText("T.C. No:");

        tcNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcNoTextActionPerformed(evt);
            }
        });

        telNoLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        telNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        telNoLabel.setText("Telefon No:");

        telNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telNoTextActionPerformed(evt);
            }
        });

        kisiselBilgilerLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        kisiselBilgilerLabel1.setText("Kişisel Bilgiler");

        GuvenlikSorusuLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        GuvenlikSorusuLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        GuvenlikSorusuLabel.setText("Ad Soyad :");

        guvenlikSorusu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        guvenlikSorusu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Evcil hayvanınızın adı nedir?", "İlkokul öğretmeninizin adı nedir?", "En sevdiğiniz nesne nedir?", "Ya da rastgele cümle girin(önerilir)." }));
        guvenlikSorusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guvenlikSorusuActionPerformed(evt);
            }
        });

        guvenlikCevabiLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        guvenlikCevabiLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        guvenlikCevabiLabel.setText("Güvenlik Sorusu :");

        guvenlikCevabiText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guvenlikCevabiTextActionPerformed(evt);
            }
        });

        cevapButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cevapButton.setText("Başvur");
        cevapButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cevapButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cevapButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cevapButtonMouseExited(evt);
            }
        });
        cevapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cevapButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout basvuruEkraniPanelLayout = new javax.swing.GroupLayout(basvuruEkraniPanel);
        basvuruEkraniPanel.setLayout(basvuruEkraniPanelLayout);
        basvuruEkraniPanelLayout.setHorizontalGroup(
            basvuruEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basvuruEkraniPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(basvuruEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(basvuruEkraniPanelLayout.createSequentialGroup()
                        .addComponent(telNoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(telNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(basvuruEkraniPanelLayout.createSequentialGroup()
                        .addComponent(tcNoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(tcNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(basvuruEkraniPanelLayout.createSequentialGroup()
                        .addComponent(GuvenlikSorusuLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(adSoyadText, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(basvuruEkraniPanelLayout.createSequentialGroup()
                        .addGroup(basvuruEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(adSoyadLabel)
                            .addComponent(kisiselBilgilerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guvenlikCevabiLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(basvuruEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(guvenlikSorusu, 0, 194, Short.MAX_VALUE)
                            .addComponent(guvenlikCevabiText))))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basvuruEkraniPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cevapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
            .addGroup(basvuruEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(basvuruEkraniPanelLayout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addComponent(kisiselBilgilerLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(244, Short.MAX_VALUE)))
        );
        basvuruEkraniPanelLayout.setVerticalGroup(
            basvuruEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basvuruEkraniPanelLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(basvuruEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adSoyadText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GuvenlikSorusuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(basvuruEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tcNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tcNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(basvuruEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(kisiselBilgilerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basvuruEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guvenlikSorusu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guvenlikCevabiLabel))
                .addGap(15, 15, 15)
                .addGroup(basvuruEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adSoyadLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(guvenlikCevabiText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cevapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(basvuruEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(basvuruEkraniPanelLayout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(kisiselBilgilerLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(327, Short.MAX_VALUE)))
        );

        basvuruEkraniPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {adSoyadLabel, adSoyadText, guvenlikCevabiText, tcNoLabel, tcNoText, telNoLabel, telNoText});

        basvuruEkraniPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {kisiselBilgilerLabel, kisiselBilgilerLabel1});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(basvuruEkraniPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(basvuruEkraniPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    @Override
    public void getEdits() {
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        basvuruEkraniPanel.setFocusable(true);
        TextAyarlari.setOnlyAlphabet(adSoyadText);
        TextAyarlari.setOnlyNumber(tcNoText);
        TextAyarlari.setOnlyNumber(telNoText);
        TextAyarlari.setMaxLimit(tcNoText, 11);
        TextAyarlari.setMaxLimit(telNoText, 11);
        
        
        
    }

    @Override
    public boolean bilgilerGecerliMi() {
        return TextAyarlari.texAlanlariDolumu(basvuruEkraniPanel);
        
        }

    @Override
    public HesapBilgileri getHesapBilgileri() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

  
    

    public KullaniciBasvuru getKullaniciBasvuruObject() {
        if(this.kullaniciBasvuruObject==null)
        {
            kullaniciBasvuruObject= new KullaniciBasvuru();
        }
        return kullaniciBasvuruObject;
    }
     
    
    private void adSoyadTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adSoyadTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adSoyadTextActionPerformed

    private void tcNoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcNoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcNoTextActionPerformed

    private void telNoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telNoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telNoTextActionPerformed

    private void guvenlikSorusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guvenlikSorusuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guvenlikSorusuActionPerformed

    private void guvenlikCevabiTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guvenlikCevabiTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guvenlikCevabiTextActionPerformed

    private void cevapButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cevapButtonMouseEntered
        ButonAyarlari.setBg(cevapButton, Color.LIGHT_GRAY, Color.BLUE);
    }//GEN-LAST:event_cevapButtonMouseEntered

    private void cevapButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cevapButtonMouseExited
        ButonAyarlari.setOriginalBg(cevapButton);
    }//GEN-LAST:event_cevapButtonMouseExited

    private void cevapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cevapButtonActionPerformed
        
        if(this.bilgilerGecerliMi())
        {
            this.basvuruyuGerceklestir();
        }
        else
        {
            Dialogs.bosOlamazMesaji(this);
        }
                
        
    }//GEN-LAST:event_cevapButtonActionPerformed

    private void basvuruyuGerceklestir()
    {
        this.getKullaniciBasvuruObject().setAdSoyad(this.adSoyadText.getText().trim());
        this.getKullaniciBasvuruObject().setTcNo(this.tcNoText.getText());
        this.getKullaniciBasvuruObject().setTelNo(this.telNoText.getText());
        this.getKullaniciBasvuruObject().setGuvenlikSorusu(String.valueOf(this.guvenlikSorusu.getSelectedItem()));
        this.getKullaniciBasvuruObject().setGuvenlikCevap(this.guvenlikCevabiText.getText().trim());
        
        this.getKullaniciBasvuruObject().setMusteriNo(this.randomMusteriNoAl());
        this.getKullaniciBasvuruObject().setSifre(this.randomSifreAl());
        
        if(this.getKullaniciBasvuruObject().basvuruOnaylandiMi())
        {
            Dialogs.ozelMesaj(this, "Başvurunuz kabul edilmiştir."+"Müşteri Numaranız : "
                                 +this.getKullaniciBasvuruObject().getMusteriNo()
                                +"\nŞifreniz : "+this.getKullaniciBasvuruObject().getSifre());
            ActionAyarlari.setVisible(this, new girisEkrani());
        }
        else
        {
            Dialogs.ozelMesaj(this, "Başvurunuz kabul edilmemiştir.\n"
                                    +"Lütfen bilgilerinizi kontrol edin.");
        }
    }
    
    
    private String randomMusteriNoAl()
    {
        String musteriNo = null;
        
        do
        {
        musteriNo=String.valueOf(1000000 + (int)(Math.random() * 9000000));
        }while (this.getKullaniciBasvuruObject().musteriNoTablodaVarMi());
            
        return musteriNo;
        
    }
    
    private String randomSifreAl()
    {
        String sifre;
        sifre=String.valueOf(1000+(int)(Math.random()*9000));
        return sifre;
    }
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(basvuruEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(basvuruEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(basvuruEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(basvuruEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new basvuruEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GuvenlikSorusuLabel;
    private javax.swing.JLabel adSoyadLabel;
    private javax.swing.JTextField adSoyadText;
    private javax.swing.JPanel basvuruEkraniPanel;
    private javax.swing.JButton cevapButton;
    private javax.swing.JLabel guvenlikCevabiLabel;
    private javax.swing.JTextField guvenlikCevabiText;
    private javax.swing.JComboBox<String> guvenlikSorusu;
    private javax.swing.JLabel kisiselBilgilerLabel;
    private javax.swing.JLabel kisiselBilgilerLabel1;
    private javax.swing.JLabel tcNoLabel;
    private javax.swing.JTextField tcNoText;
    private javax.swing.JLabel telNoLabel;
    private javax.swing.JTextField telNoText;
    // End of variables declaration//GEN-END:variables
}
