/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import database.IBilgiController;
import database.transactons.HesapBilgileri;
import gui.ayarlari.ActionAyarlari;
import gui.ayarlari.ButonAyarlari;
import gui.ayarlari.Dialogs;
import gui.ayarlari.IDuzenleyici;
import gui.ayarlari.IconAyarlari;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JButton;


public class hesapEkrani extends javax.swing.JFrame implements IDuzenleyici,IBilgiController{

    /**
     * Creates new form hesapEkrani
     */
    public hesapEkrani() {
        initComponents();
        getEdits();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hesapEkraniPanel = new javax.swing.JPanel();
        hosgeldinLabel = new javax.swing.JLabel();
        adiSoyadiLabel = new javax.swing.JLabel();
        turkLirasiLabel = new javax.swing.JLabel();
        bakiyeLabel = new javax.swing.JLabel();
        paraCekLabel = new javax.swing.JLabel();
        paraCekButton = new javax.swing.JButton();
        paraYatirLabel = new javax.swing.JLabel();
        paraYatirButton = new javax.swing.JButton();
        havaleLabel = new javax.swing.JLabel();
        havaleButton = new javax.swing.JButton();
        odemelerLabel = new javax.swing.JLabel();
        odemelerButton = new javax.swing.JButton();
        cıkısLabel = new javax.swing.JLabel();
        ayarlarLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hesap Ekranı");

        hesapEkraniPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hosgeldinLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hosgeldinLabel.setForeground(new java.awt.Color(153, 0, 0));
        hosgeldinLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hosgeldinLabel.setText("HOŞGELDİN");
        hesapEkraniPanel.add(hosgeldinLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 65, 200, 30));

        adiSoyadiLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        adiSoyadiLabel.setForeground(new java.awt.Color(153, 0, 0));
        adiSoyadiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adiSoyadiLabel.setText("[ADI SOYADI]");
        hesapEkraniPanel.add(adiSoyadiLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 101, 324, 33));

        turkLirasiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        turkLirasiLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Iconlar/turkishLiraIcon.png"))); // NOI18N
        hesapEkraniPanel.add(turkLirasiLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 162, 82, 73));

        bakiyeLabel.setFont(new java.awt.Font("Tahoma", 0, 42)); // NOI18N
        bakiyeLabel.setForeground(new java.awt.Color(204, 0, 0));
        bakiyeLabel.setText("[BAKİYE]");
        hesapEkraniPanel.add(bakiyeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 176, 291, 50));

        paraCekLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paraCekLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Iconlar/withdrawIcon2.png"))); // NOI18N
        hesapEkraniPanel.add(paraCekLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 297, 88, 77));

        paraCekButton.setText("Para Çek");
        paraCekButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paraCekButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paraCekButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paraCekButtonMouseExited(evt);
            }
        });
        paraCekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paraCekButtonActionPerformed(evt);
            }
        });
        hesapEkraniPanel.add(paraCekButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 392, 80, 34));

        paraYatirLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paraYatirLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Iconlar/depositeIcon2.png"))); // NOI18N
        hesapEkraniPanel.add(paraYatirLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 297, 88, 77));

        paraYatirButton.setText("Para Yatır");
        paraYatirButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paraYatirButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paraYatirButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paraYatirButtonMouseExited(evt);
            }
        });
        paraYatirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paraYatirButtonActionPerformed(evt);
            }
        });
        hesapEkraniPanel.add(paraYatirButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 392, 88, 34));

        havaleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        havaleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Iconlar/transferIcon.png"))); // NOI18N
        hesapEkraniPanel.add(havaleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 297, 88, 77));

        havaleButton.setText("Havale");
        havaleButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        havaleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                havaleButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                havaleButtonMouseExited(evt);
            }
        });
        havaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                havaleButtonActionPerformed(evt);
            }
        });
        hesapEkraniPanel.add(havaleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 392, 80, 34));

        odemelerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        odemelerLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Iconlar/paymentIcon.png"))); // NOI18N
        hesapEkraniPanel.add(odemelerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 297, 88, 77));

        odemelerButton.setText("Ödemeler");
        odemelerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        odemelerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                odemelerButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                odemelerButtonMouseExited(evt);
            }
        });
        odemelerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odemelerButtonActionPerformed(evt);
            }
        });
        hesapEkraniPanel.add(odemelerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 392, 80, 34));

        cıkısLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Iconlar/logoutLabel.png"))); // NOI18N
        cıkısLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cıkısLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cıkısLabelMouseClicked(evt);
            }
        });
        hesapEkraniPanel.add(cıkısLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 60, 70));

        ayarlarLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Iconlar/settingIcon.png"))); // NOI18N
        ayarlarLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ayarlarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ayarlarLabelMouseClicked(evt);
            }
        });
        hesapEkraniPanel.add(ayarlarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 60, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hesapEkraniPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(hesapEkraniPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void setBgFg(Component c)
    {
        ButonAyarlari.setBg((JButton)c, Color.BLACK, Color.WHITE);
    }
    
    private void paraCekButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paraCekButtonMouseEntered
        this.setBgFg(evt.getComponent());
        IconAyarlari.changeIcon(paraCekLabel,"withdrawIcon");
    }//GEN-LAST:event_paraCekButtonMouseEntered

    private void paraCekButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paraCekButtonMouseExited
        ButonAyarlari.setOriginalBg((JButton)evt.getComponent());
        IconAyarlari.setOriginalIcon(paraCekLabel);
    }//GEN-LAST:event_paraCekButtonMouseExited

    private void paraYatirButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paraYatirButtonMouseEntered
        this.setBgFg(evt.getComponent());
        IconAyarlari.changeIcon(paraYatirLabel,"depositeIcon");
    }//GEN-LAST:event_paraYatirButtonMouseEntered

    private void paraYatirButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paraYatirButtonMouseExited
        ButonAyarlari.setOriginalBg((JButton)evt.getComponent());
        IconAyarlari.setOriginalIcon(paraYatirLabel);
    }//GEN-LAST:event_paraYatirButtonMouseExited

    private void havaleButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_havaleButtonMouseEntered
        this.setBgFg(evt.getComponent());
        IconAyarlari.changeIcon(havaleLabel,"transferIcon2");
    }//GEN-LAST:event_havaleButtonMouseEntered

    private void havaleButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_havaleButtonMouseExited
        ButonAyarlari.setOriginalBg((JButton)evt.getComponent());
        IconAyarlari.setOriginalIcon(havaleLabel);
    }//GEN-LAST:event_havaleButtonMouseExited

    private void odemelerButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_odemelerButtonMouseExited
        ButonAyarlari.setOriginalBg((JButton)evt.getComponent());
        IconAyarlari.setOriginalIcon(odemelerLabel);
        
    }//GEN-LAST:event_odemelerButtonMouseExited

    private void cıkısLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cıkısLabelMouseClicked
        String question="Hesabınızdan çıkış yapılacaktır.\n"
                + "Onaylıyor musunuz?";
        if(Dialogs.onayMesajiGoster(this, question)==1)
        {
            this.cıkısYap();
        }
    }//GEN-LAST:event_cıkısLabelMouseClicked
    private void cıkısYap()
     {
         getHesapBilgileri().cıkısYap();
         ActionAyarlari.setVisible(this, new girisEkrani());
     }
           
    private void ayarlarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ayarlarLabelMouseClicked
        ActionAyarlari.setVisible(this, new ayarlarEkrani());
    }//GEN-LAST:event_ayarlarLabelMouseClicked

    private void odemelerButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_odemelerButtonMouseEntered
        this.setBgFg(evt.getComponent());
        IconAyarlari.changeIcon(odemelerLabel,"paymentIcon2");
    }//GEN-LAST:event_odemelerButtonMouseEntered

    private void paraCekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paraCekButtonActionPerformed
        ActionAyarlari.setVisible(this, new paraCekmeEkrani());
    }//GEN-LAST:event_paraCekButtonActionPerformed

    private void paraYatirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paraYatirButtonActionPerformed
        ActionAyarlari.setVisible(this, new paraYatirmaEkrani());
    }//GEN-LAST:event_paraYatirButtonActionPerformed

    private void havaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_havaleButtonActionPerformed
        ActionAyarlari.setVisible(this, new havaleEkrani());
    }//GEN-LAST:event_havaleButtonActionPerformed

    private void odemelerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odemelerButtonActionPerformed
        ActionAyarlari.setVisible(this, new odemelerEkrani());
    }//GEN-LAST:event_odemelerButtonActionPerformed

    @Override
    public void getEdits() 
    {
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        hesapEkraniPanel.setFocusable(true);
        this.adiSoyadiLabel.setText(getHesapBilgileri().getAdSoyad());
        this.bakiyeLabel.setText(String.valueOf(getHesapBilgileri().getBakiye()));
    }

    @Override
    public boolean bilgilerGecerliMi() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public HesapBilgileri getHesapBilgileri() {
    return HesapBilgileri.getInstance();
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hesapEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hesapEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hesapEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hesapEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hesapEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adiSoyadiLabel;
    private javax.swing.JLabel ayarlarLabel;
    private javax.swing.JLabel bakiyeLabel;
    private javax.swing.JLabel cıkısLabel;
    private javax.swing.JButton havaleButton;
    private javax.swing.JLabel havaleLabel;
    private javax.swing.JPanel hesapEkraniPanel;
    private javax.swing.JLabel hosgeldinLabel;
    private javax.swing.JButton odemelerButton;
    private javax.swing.JLabel odemelerLabel;
    private javax.swing.JButton paraCekButton;
    private javax.swing.JLabel paraCekLabel;
    private javax.swing.JButton paraYatirButton;
    private javax.swing.JLabel paraYatirLabel;
    private javax.swing.JLabel turkLirasiLabel;
    // End of variables declaration//GEN-END:variables
}
