/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import database.IBilgiController;
import database.transactons.FaturaOdemeleri;
import database.transactons.HesapBilgileri;
import gui.ayarlari.ActionAyarlari;
import gui.ayarlari.ButonAyarlari;
import gui.ayarlari.Dialogs;
import gui.ayarlari.IDuzenleyici;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dialog;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class odemelerEkrani extends javax.swing.JFrame implements IDuzenleyici,IBilgiController{

    
    private FaturaOdemeleri faturaOdemeleriObject=null;
    
    public odemelerEkrani() {
        initComponents();
        getEdits();
    }

    @Override
    public void getEdits() {
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        odemelerPanel.setFocusable(true);
        this.kullaniciAdiSoyadiLabel.setText(this.getHesapBilgileri().getAdSoyad());
        this.elektrikBorcuLabel.setText(String.valueOf(this.getHesapBilgileri().getElektrikFaturasi()));
        this.suBorcuLabel.setText(String.valueOf(this.getHesapBilgileri().getSuFaturasi()));
        this.dogalgazBorcuLabel.setText(String.valueOf(this.getHesapBilgileri().getDogalgazFaturasi()));
        this.internetBorcuLabel.setText(String.valueOf(this.getHesapBilgileri().getInternetFaturasi()));
        
        
    }

    public FaturaOdemeleri getFaturaOdemeleriObject() {
        if(faturaOdemeleriObject==null)
        {
            faturaOdemeleriObject=new FaturaOdemeleri();
        }
        return faturaOdemeleriObject;
    }
     
    
    @Override
    public boolean bilgilerGecerliMi() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public HesapBilgileri getHesapBilgileri() {
         return HesapBilgileri.getInstance();
    }
    
private void setBgFg(Component c)
    {
        ButonAyarlari.setBg((JButton)c, Color.BLACK, Color.WHITE);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        odemelerPanel = new javax.swing.JPanel();
        geriIcon = new javax.swing.JLabel();
        kullaniciAdiSoyadiLabel = new javax.swing.JLabel();
        elektrikLabel = new javax.swing.JLabel();
        elektrikBorcuLabel = new javax.swing.JLabel();
        elektrikOdeButton = new javax.swing.JButton();
        suLabel = new javax.swing.JLabel();
        suBorcuLabel = new javax.swing.JLabel();
        suOdeButton = new javax.swing.JButton();
        dogalgazLabel = new javax.swing.JLabel();
        dogalgazBorcuLabel = new javax.swing.JLabel();
        dogalgazOdeButton = new javax.swing.JButton();
        internetLabel = new javax.swing.JLabel();
        internetBorcuLabel = new javax.swing.JLabel();
        internetOdeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        odemelerPanel.setBackground(new java.awt.Color(255, 204, 204));
        odemelerPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        geriIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Iconlar/preiousIcon.png"))); // NOI18N
        geriIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        geriIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                geriIconMouseClicked(evt);
            }
        });

        kullaniciAdiSoyadiLabel.setBackground(new java.awt.Color(255, 204, 204));
        kullaniciAdiSoyadiLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        kullaniciAdiSoyadiLabel.setForeground(new java.awt.Color(153, 0, 0));
        kullaniciAdiSoyadiLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kullaniciAdiSoyadiLabel.setText("SAYIN [ADI SOYADI]");

        elektrikLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        elektrikLabel.setText("Toplam Elektrik Borcunuz :");

        elektrikBorcuLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        elektrikBorcuLabel.setText("[ELKTRK BORCU]");

        elektrikOdeButton.setBackground(new java.awt.Color(255, 204, 204));
        elektrikOdeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        elektrikOdeButton.setText("ÖDE");
        elektrikOdeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                elektrikOdeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                elektrikOdeButtonMouseExited(evt);
            }
        });
        elektrikOdeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elektrikOdeButtonActionPerformed(evt);
            }
        });

        suLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        suLabel.setText("Toplam Su Borcunuz :");

        suBorcuLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        suBorcuLabel.setText("[SU BORCU]");

        suOdeButton.setBackground(new java.awt.Color(102, 102, 255));
        suOdeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        suOdeButton.setText("ÖDE");
        suOdeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                suOdeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                suOdeButtonMouseExited(evt);
            }
        });
        suOdeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suOdeButtonActionPerformed(evt);
            }
        });

        dogalgazLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dogalgazLabel.setText("Toplam Doğalgaz Borcunuz :");

        dogalgazBorcuLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dogalgazBorcuLabel.setText("[DGLGZ BORCU]");

        dogalgazOdeButton.setBackground(new java.awt.Color(153, 255, 153));
        dogalgazOdeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dogalgazOdeButton.setText("ÖDE");
        dogalgazOdeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dogalgazOdeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dogalgazOdeButtonMouseExited(evt);
            }
        });
        dogalgazOdeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dogalgazOdeButtonActionPerformed(evt);
            }
        });

        internetLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        internetLabel.setText("Toplam İnternet Borcunuz :");

        internetBorcuLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        internetBorcuLabel.setText("[INTERNET BORCU]");

        internetOdeButton.setBackground(new java.awt.Color(255, 153, 153));
        internetOdeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        internetOdeButton.setText("ÖDE");
        internetOdeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                internetOdeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                internetOdeButtonMouseExited(evt);
            }
        });
        internetOdeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internetOdeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout odemelerPanelLayout = new javax.swing.GroupLayout(odemelerPanel);
        odemelerPanel.setLayout(odemelerPanelLayout);
        odemelerPanelLayout.setHorizontalGroup(
            odemelerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(odemelerPanelLayout.createSequentialGroup()
                .addGroup(odemelerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(odemelerPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(geriIcon))
                    .addGroup(odemelerPanelLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(kullaniciAdiSoyadiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(odemelerPanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(odemelerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(elektrikLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(suLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dogalgazLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(internetLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(odemelerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(suBorcuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dogalgazBorcuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(elektrikBorcuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(internetBorcuLabel))
                        .addGap(46, 46, 46)
                        .addGroup(odemelerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(elektrikOdeButton)
                            .addComponent(suOdeButton)
                            .addComponent(dogalgazOdeButton)
                            .addComponent(internetOdeButton))))
                .addGap(18, 18, 18))
        );

        odemelerPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dogalgazBorcuLabel, elektrikBorcuLabel, internetBorcuLabel, suBorcuLabel});

        odemelerPanelLayout.setVerticalGroup(
            odemelerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(odemelerPanelLayout.createSequentialGroup()
                .addGroup(odemelerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(odemelerPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(geriIcon)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(odemelerPanelLayout.createSequentialGroup()
                        .addContainerGap(56, Short.MAX_VALUE)
                        .addComponent(kullaniciAdiSoyadiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(odemelerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(elektrikLabel)
                            .addComponent(elektrikBorcuLabel)
                            .addComponent(elektrikOdeButton))
                        .addGap(24, 24, 24)
                        .addGroup(odemelerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(suLabel)
                            .addComponent(suBorcuLabel)
                            .addComponent(suOdeButton))
                        .addGap(18, 18, 18)
                        .addGroup(odemelerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dogalgazLabel)
                            .addComponent(dogalgazBorcuLabel)
                            .addComponent(dogalgazOdeButton))
                        .addGap(10, 10, 10)))
                .addGap(8, 8, 8)
                .addGroup(odemelerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(internetLabel)
                    .addComponent(internetBorcuLabel)
                    .addComponent(internetOdeButton))
                .addGap(36, 36, 36))
        );

        odemelerPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dogalgazBorcuLabel, dogalgazLabel, dogalgazOdeButton, elektrikBorcuLabel, elektrikLabel, elektrikOdeButton, internetBorcuLabel, internetLabel, internetOdeButton, suBorcuLabel});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(odemelerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(odemelerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void geriIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geriIconMouseClicked
        ActionAyarlari.setVisible(this, new hesapEkrani());
    }//GEN-LAST:event_geriIconMouseClicked

    private void elektrikOdeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elektrikOdeButtonMouseEntered
        this.setBgFg(evt.getComponent());
    }//GEN-LAST:event_elektrikOdeButtonMouseEntered

    private void elektrikOdeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elektrikOdeButtonMouseExited
        ButonAyarlari.setOriginalBg(elektrikOdeButton);
        
    }//GEN-LAST:event_elektrikOdeButtonMouseExited

    private void suOdeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suOdeButtonMouseEntered
        this.setBgFg(evt.getComponent());
        
    }//GEN-LAST:event_suOdeButtonMouseEntered

    private void suOdeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suOdeButtonMouseExited
        ButonAyarlari.setOriginalBg(suOdeButton);
        
    }//GEN-LAST:event_suOdeButtonMouseExited

    private void dogalgazOdeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dogalgazOdeButtonMouseEntered
        this.setBgFg(evt.getComponent());
        
    }//GEN-LAST:event_dogalgazOdeButtonMouseEntered

    private void dogalgazOdeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dogalgazOdeButtonMouseExited
        ButonAyarlari.setOriginalBg(dogalgazOdeButton);
        
    }//GEN-LAST:event_dogalgazOdeButtonMouseExited

    private void internetOdeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_internetOdeButtonMouseEntered
        this.setBgFg(evt.getComponent());
        
    }//GEN-LAST:event_internetOdeButtonMouseEntered

    private void internetOdeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_internetOdeButtonMouseExited
        ButonAyarlari.setOriginalBg(internetOdeButton);
        
    }//GEN-LAST:event_internetOdeButtonMouseExited

    private void elektrikOdeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elektrikOdeButtonActionPerformed
        double elektrikTutari= Double.valueOf(this.elektrikBorcuLabel.getText());
        if(this.faturaOncedenOdenmisMi(elektrikTutari))
        {
            Dialogs.ozelMesaj(this, "Elektrik faturası zaten ödenmiş!");
        }else
        {
            this.faturayiOde("elektrik", elektrikTutari);
        }
    }//GEN-LAST:event_elektrikOdeButtonActionPerformed

    private void suOdeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suOdeButtonActionPerformed
        double suTutari= Double.valueOf(this.suBorcuLabel.getText());
        if(this.faturaOncedenOdenmisMi(suTutari))
        {
            Dialogs.ozelMesaj(this, "Su faturası zaten ödenmiş!");
        }else
        {
            this.faturayiOde("su", suTutari);
        }
    }//GEN-LAST:event_suOdeButtonActionPerformed

    private void dogalgazOdeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dogalgazOdeButtonActionPerformed
        double dogalgazTutari= Double.valueOf(this.dogalgazBorcuLabel.getText());
        if(this.faturaOncedenOdenmisMi(dogalgazTutari))
        {
            Dialogs.ozelMesaj(this, "Doğalgaz faturası zaten ödenmiş!");
        }else
        {
            this.faturayiOde("dogalgaz", dogalgazTutari);
        }
    }//GEN-LAST:event_dogalgazOdeButtonActionPerformed

    private void internetOdeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internetOdeButtonActionPerformed
        double internetTutari= Double.valueOf(this.elektrikBorcuLabel.getText());
        if(this.faturaOncedenOdenmisMi(internetTutari))
        {
            Dialogs.ozelMesaj(this, "İnternet faturası zaten ödenmiş!");
        }else
        {
            this.faturayiOde("internet", internetTutari);
        }
    }//GEN-LAST:event_internetOdeButtonActionPerformed

    private boolean faturaOncedenOdenmisMi(double odenecekMiktar)
    {
        return odenecekMiktar == 0.0 ;
    }
    
    private void faturayiOde(String faturaIsmi,Double faturaTutari)
    {
        this.getFaturaOdemeleriObject().setFaturaTutari(faturaTutari);
        this.getFaturaOdemeleriObject().setFaturaIsmi(faturaIsmi);
        
        if(getFaturaOdemeleriObject().faturaOdendiMi())
        {
            Dialogs.ozelMesaj(this, "Faturanız başarıyla ödenmiştir.");
            ActionAyarlari.setVisible(this, new hesapEkrani());
        }else
        {
            Dialogs.ozelMesaj(this, "İşlem başarısız.");
        }
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(odemelerEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(odemelerEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(odemelerEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(odemelerEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new odemelerEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dogalgazBorcuLabel;
    private javax.swing.JLabel dogalgazLabel;
    private javax.swing.JButton dogalgazOdeButton;
    private javax.swing.JLabel elektrikBorcuLabel;
    private javax.swing.JLabel elektrikLabel;
    private javax.swing.JButton elektrikOdeButton;
    private javax.swing.JLabel geriIcon;
    private javax.swing.JLabel internetBorcuLabel;
    private javax.swing.JLabel internetLabel;
    private javax.swing.JButton internetOdeButton;
    private javax.swing.JLabel kullaniciAdiSoyadiLabel;
    private javax.swing.JPanel odemelerPanel;
    private javax.swing.JLabel suBorcuLabel;
    private javax.swing.JLabel suLabel;
    private javax.swing.JButton suOdeButton;
    // End of variables declaration//GEN-END:variables
}
