/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import database.IBilgiController;
import database.transactons.HesapBilgileri;
import database.transactons.SifreYenileme;
import gui.ayarlari.ActionAyarlari;
import gui.ayarlari.ButonAyarlari;
import gui.ayarlari.Dialogs;
import gui.ayarlari.IDuzenleyici;
import gui.ayarlari.TextAyarlari;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author LENOVO
 */
public class sifreYenilemeEkrani extends javax.swing.JFrame implements IDuzenleyici,IBilgiController{

    
    private SifreYenileme sifreYenilemeObject=null;
            
    public sifreYenilemeEkrani() {
        initComponents();
        getEdits();
        
    }

    @Override
    public void getEdits() {
       this.setLocationRelativeTo(null);
       this.setResizable(false);
       this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
       sifreYenilemeEkraniPanel.setFocusable(true);
        TextAyarlari.setOnlyNumber(tcNoText);
        TextAyarlari.setMaxLimit(tcNoText, 11);
        TextAyarlari.setOnlyNumber(telNoText);
        TextAyarlari.setMaxLimit(telNoText, 11);
        if(getHesapBilgileri().getKullanici_id()==0)
        {
            this.eskiSifre.setEnabled(false);
        }
        
       
    }

    public SifreYenileme getSifreYenilemeObject() {
        if(sifreYenilemeObject==null)
        {
            sifreYenilemeObject=new SifreYenileme();
        }
        return sifreYenilemeObject;
    }
    

    @Override
    public boolean bilgilerGecerliMi() {
       return TextAyarlari.texAlanlariDolumu(this.sifreYenilemeEkraniPanel);
    }

    @Override
    public HesapBilgileri getHesapBilgileri() {
      return HesapBilgileri.getInstance();
    }
    

    public JPasswordField getEskiSifre() {
        return eskiSifre;
    }

    
    
   private boolean isEnableEskiSifreText()
   {
       return this.getEskiSifre().isEnabled();
   }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sifreYenilemeEkraniPanel = new javax.swing.JPanel();
        geriIcon3 = new javax.swing.JLabel();
        baslıkLabel = new javax.swing.JLabel();
        tcNoLabel = new javax.swing.JLabel();
        tcNoText = new javax.swing.JTextField();
        telNoLabel = new javax.swing.JLabel();
        telNoText = new javax.swing.JTextField();
        guvenlikLabel = new javax.swing.JLabel();
        guvenlikText = new javax.swing.JTextField();
        eskiSifreLabel = new javax.swing.JLabel();
        eskiSifre = new javax.swing.JPasswordField();
        yeniSifreLabel = new javax.swing.JLabel();
        yeniSifreTekrarLabel = new javax.swing.JLabel();
        sifreYenileButton = new javax.swing.JButton();
        yeniSifre = new javax.swing.JPasswordField();
        yeniSifreTekrar = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sifreYenilemeEkraniPanel.setBackground(new java.awt.Color(255, 255, 204));

        geriIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Iconlar/preiousIcon.png"))); // NOI18N
        geriIcon3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        geriIcon3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                geriIcon3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                geriIcon3MouseEntered(evt);
            }
        });

        baslıkLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        baslıkLabel.setForeground(new java.awt.Color(153, 0, 51));
        baslıkLabel.setText("Şifre Yenileme");

        tcNoLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tcNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tcNoLabel.setText("T.C. No :");

        tcNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcNoTextActionPerformed(evt);
            }
        });

        telNoLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        telNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        telNoLabel.setText("Telefon No :");

        telNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telNoTextActionPerformed(evt);
            }
        });

        guvenlikLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        guvenlikLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        guvenlikLabel.setText("Güvenlik Sorusu Cevabı :");

        guvenlikText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guvenlikTextActionPerformed(evt);
            }
        });

        eskiSifreLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        eskiSifreLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        eskiSifreLabel.setText("Eski Şifre :");

        eskiSifre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eskiSifreActionPerformed(evt);
            }
        });

        yeniSifreLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        yeniSifreLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        yeniSifreLabel.setText("Yeni Şifre :");

        yeniSifreTekrarLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        yeniSifreTekrarLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        yeniSifreTekrarLabel.setText("Yeni Şifre Tekrar :");

        sifreYenileButton.setBackground(new java.awt.Color(51, 0, 204));
        sifreYenileButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sifreYenileButton.setText("Şifreyi Yenile");
        sifreYenileButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sifreYenileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sifreYenileButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sifreYenileButtonMouseExited(evt);
            }
        });
        sifreYenileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifreYenileButtonActionPerformed(evt);
            }
        });

        yeniSifre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yeniSifreActionPerformed(evt);
            }
        });

        yeniSifreTekrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yeniSifreTekrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sifreYenilemeEkraniPanelLayout = new javax.swing.GroupLayout(sifreYenilemeEkraniPanel);
        sifreYenilemeEkraniPanel.setLayout(sifreYenilemeEkraniPanelLayout);
        sifreYenilemeEkraniPanelLayout.setHorizontalGroup(
            sifreYenilemeEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sifreYenilemeEkraniPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(geriIcon3)
                .addGap(38, 38, 38)
                .addGroup(sifreYenilemeEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sifreYenilemeEkraniPanelLayout.createSequentialGroup()
                        .addGroup(sifreYenilemeEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tcNoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(telNoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(sifreYenilemeEkraniPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(sifreYenilemeEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(eskiSifreLabel)
                                    .addComponent(guvenlikLabel)
                                    .addComponent(yeniSifreLabel)
                                    .addComponent(yeniSifreTekrarLabel))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sifreYenilemeEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sifreYenilemeEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(sifreYenilemeEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tcNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telNoText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(guvenlikText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(eskiSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yeniSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yeniSifreTekrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(sifreYenilemeEkraniPanelLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(sifreYenileButton)))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(sifreYenilemeEkraniPanelLayout.createSequentialGroup()
                        .addComponent(baslıkLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        sifreYenilemeEkraniPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {eskiSifreLabel, guvenlikLabel});

        sifreYenilemeEkraniPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {eskiSifre, guvenlikText, yeniSifre, yeniSifreTekrar});

        sifreYenilemeEkraniPanelLayout.setVerticalGroup(
            sifreYenilemeEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sifreYenilemeEkraniPanelLayout.createSequentialGroup()
                .addGroup(sifreYenilemeEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sifreYenilemeEkraniPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(geriIcon3))
                    .addGroup(sifreYenilemeEkraniPanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(baslıkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(sifreYenilemeEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tcNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tcNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sifreYenilemeEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sifreYenilemeEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guvenlikLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guvenlikText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sifreYenilemeEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eskiSifreLabel)
                    .addComponent(eskiSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sifreYenilemeEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yeniSifreLabel)
                    .addComponent(yeniSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sifreYenilemeEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yeniSifreTekrarLabel)
                    .addComponent(yeniSifreTekrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(sifreYenileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        sifreYenilemeEkraniPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {eskiSifre, eskiSifreLabel, guvenlikLabel, guvenlikText, tcNoLabel, tcNoText, telNoLabel, telNoText, yeniSifre, yeniSifreTekrar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sifreYenilemeEkraniPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sifreYenilemeEkraniPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void geriIcon3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geriIcon3MouseClicked

        if(isEnableEskiSifreText())
        {
            ActionAyarlari.setVisible(this, new ayarlarEkrani());
        }
        else
        {
            ActionAyarlari.setVisible(this, new girisEkrani());
        }
    }//GEN-LAST:event_geriIcon3MouseClicked

    private void geriIcon3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geriIcon3MouseEntered

    }//GEN-LAST:event_geriIcon3MouseEntered

    private void tcNoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcNoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcNoTextActionPerformed

    private void telNoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telNoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telNoTextActionPerformed

    private void guvenlikTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guvenlikTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guvenlikTextActionPerformed

    private void eskiSifreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eskiSifreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eskiSifreActionPerformed

    private void yeniSifreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yeniSifreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yeniSifreActionPerformed

    private void yeniSifreTekrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yeniSifreTekrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yeniSifreTekrarActionPerformed

    private void sifreYenileButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sifreYenileButtonMouseEntered
        ButonAyarlari.setBg(sifreYenileButton, Color.LIGHT_GRAY, Color.BLUE);
    }//GEN-LAST:event_sifreYenileButtonMouseEntered

    private void sifreYenileButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sifreYenileButtonMouseExited
        ButonAyarlari.setOriginalBg(sifreYenileButton);
    }//GEN-LAST:event_sifreYenileButtonMouseExited

    private void sifreYenileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifreYenileButtonActionPerformed
       if(bilgilerGecerliMi())
       {
           this.sifreyiYenile();
       }else{
           Dialogs.bosOlamazMesaji(this);
       }
    }//GEN-LAST:event_sifreYenileButtonActionPerformed
       private void sifreyiYenile() {
       String yeniiSifre=String.valueOf(this.yeniSifre.getPassword());
       String sifreTekrar=String.valueOf(this.yeniSifreTekrar.getPassword());
       if(yeniiSifre.equals(sifreTekrar))
       {
           this.sifreyiOnayla();
       }
       else
       {
           Dialogs.ozelMesaj(this, "Şifreler uyuşmuyor!");
       }
       }
        private void sifreyiOnayla() {
        this.getSifreYenilemeObject().setTcNo(this.tcNoText.getText());
        this.getSifreYenilemeObject().setTelNo(this.telNoText.getText());
        this.getSifreYenilemeObject().setGuvenlikCevap(this.guvenlikText.getText());
        if(this.isEnableEskiSifreText())
        {
            this.getSifreYenilemeObject().setEskiSifre(String.valueOf(this.eskiSifre.getPassword()));
        }
        this.getSifreYenilemeObject().setYeniSifre(String.valueOf(this.yeniSifre.getPassword()));
        if(this.getSifreYenilemeObject().sifreYenilendiMi())
        {
            Dialogs.ozelMesaj(this, "Şifreniz başarıyla yenilendi.");
            if(this.isEnableEskiSifreText())
            {
                ActionAyarlari.setVisible(this, new hesapEkrani());
            }else{
                ActionAyarlari.setVisible(this, new girisEkrani());
            }
        }else{
            Dialogs.ozelMesaj(this, "Şifreniz yenilenemedi.\n"
                    + "Lütfen bilgilerinizi kontrol edin.");
        }
        }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sifreYenilemeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sifreYenilemeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sifreYenilemeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sifreYenilemeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sifreYenilemeEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel baslıkLabel;
    private javax.swing.JPasswordField eskiSifre;
    private javax.swing.JLabel eskiSifreLabel;
    private javax.swing.JLabel geriIcon3;
    private javax.swing.JLabel guvenlikLabel;
    private javax.swing.JTextField guvenlikText;
    private javax.swing.JButton sifreYenileButton;
    private javax.swing.JPanel sifreYenilemeEkraniPanel;
    private javax.swing.JLabel tcNoLabel;
    private javax.swing.JTextField tcNoText;
    private javax.swing.JLabel telNoLabel;
    private javax.swing.JTextField telNoText;
    private javax.swing.JPasswordField yeniSifre;
    private javax.swing.JLabel yeniSifreLabel;
    private javax.swing.JPasswordField yeniSifreTekrar;
    private javax.swing.JLabel yeniSifreTekrarLabel;
    // End of variables declaration//GEN-END:variables

   

    
}
